# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "qr-code"
client_id = "7bae1ce4325d267f505591e1577391ef"
application_url = "https://sponsorship-drums-connecting-leave.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sponsorship-drums-connecting-leave.trycloudflare.com/auth/callback",
  "https://sponsorship-drums-connecting-leave.trycloudflare.com/auth/shopify/callback",
  "https://sponsorship-drums-connecting-leave.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "codewithsandhu.myshopify.com"
